### ISSUE TITLE
What if my data does not completely fit into RAM all at once?

### ISSUE THREAD

**Issue by luzuku** [lmcinnes/pynndescent#141]
Hi,

this might be a dumb question, but is there a way to use pynndescent if my data does not fit into RAM all at once?
I couldn't find anything in the documentation related to some iterative fitting.

Sort of like this:
```python
from pynndescent import NNDescent

data_batch_paths = [path0, path1, ...]
nn = NNDescent()

for path in data_batch_paths:
    batch = load(path)
    nn.step(batch)

index = nn.index
...
```

**Comment by lmcinnes** [comment]
There is the ability to update a model with a new batch of data (use the ``update`` method), but since the current version holds the data in memory (for search purposes) and doesn't do any vector quantisation / product quantisation / style compression games, if your data doesn't fit in memory then that isn't going to help. In principle there is hope that a distributed /dask version of pynndescent could be built that would allow cluster / out-of-core based indices which would likely meet your needs, but there is absolutely no time-frame for when such a thing might happen. Sorry.

**Comment by luzuku** [comment]
Thanks for you answer! Hopefully you will get the time to implement this functionality some time in the future.

**Comment by ezorita** [comment]
@lmcinnes I found this issue that might be outdated, but I was wondering whether this `update` method is still available to incrementally build the index? It does not seem to be documented.

**Comment by lmcinnes** [comment]
There is an update method, but things still need to fit in RAM. If you really need at out-of-core option there is a branch ``distributed`` that can operate with dask arrays, including distributed arrays. I never got all the features finished, so it didn't get merged, but it may be good enough for your needs.
