### ISSUE TITLE
How to store graph for further use ?

### ISSUE THREAD

**Issue by tempdeltavalue** [lmcinnes/pynndescent#156]
Want to save generated graph but I can't find needed functionality in docs :(

**Comment by lmcinnes** [comment]
The model is pickleable (or should be), so that's one approach. If you just care about the graph then you can simply save the numpy arrays of ``neighbor_graph``, or convert to a scipy sparse adjacency matrix representation and save that. If you are interested more in the latter approach then the PyNNDescentTransformer is probably a better approach as that will give the adjacency matrix directly.

**Comment by tempdeltavalue** [comment]
Thanks for answer.

What do you mean by neighbor_graph ? 

By storing I meant something that faiss has, write_index and read_index functions where's you can save and restore entire index

**Comment by lmcinnes** [comment]
Ah, if you want the whole index saved then just pickle the entire object, and load is back later.

**Comment by tempdeltavalue** [comment]
Thank you !
